-- adding genres
insert into genres (title)
values
    ('Classics'),
    ('Sci-Fi'),
    ('Fantasy'),
    ('Mystery'),
    ('Thriller'),
    ('Romance'),
    ('Historical Fiction'),
    ('Contemporary'),
    ('Horror'),
    ('Dystopian'),
    ('Adventure'),
    ('Young Adult'),
    ('Childrens'),
    ('Biography'),
    ('Autobiography'),
    ('Memoir'),
    ('Non-fiction'),
    ('Self-Help'),
    ('Psychology'),
    ('Philosophy'),
    ('History'),
    ('Science'),
    ('Business'),
    ('Poetry'),
    ('Drama'),
    ('Crime'),
    ('Comics'),
    ('Art'),
    ('Cookbooks'),
    ('Travel')
on conflict (title) do nothing;